2.1.1 Creating PyTorch tensors

In [2]:
# heights of the 46 U.S. presidents in chronological order (cm)
heights = [189, 170, 189, 163, 183, 171, 185,
           168, 173, 183, 173, 173, 175, 178,
           183, 193, 178, 173, 174, 183, 183,
           180, 168, 180, 170, 178, 182, 180,
           183, 178, 182, 188, 175, 179, 183,
           193, 182, 183, 177, 185, 188, 188,
           182, 185, 191, 183]

In [3]:
# convert the python list to a Pytorch tensor
import torch

heights_tensor = torch.tensor(heights, dtype=torch.float64)

In [4]:
# two ways of specifying tensor types
t1 = torch.IntTensor([1, 2, 3])
t2 = torch.tensor([1, 2, 3], dtype=torch.int)

print(t1)
print(t2)

tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)


In [5]:
"""
Exercise 2.1
Use two different methods to convert the Python list [5, 8, 10] into a PyTorch tensor
with 64-bit floating-point numbers in it. Consult the third row in table 2.1 for this question.
"""

tensor1 = torch.tensor([5, 8, 10], dtype=torch.float64)
tensor2 = torch.DoubleTensor([5, 8, 10])

tensor1, tensor2

(tensor([ 5.,  8., 10.], dtype=torch.float64),
 tensor([ 5.,  8., 10.], dtype=torch.float64))

In [6]:
# create a tensor of zeros with two rows and three columns (default float32)
tensor1 = torch.zeros(2, 3)

tensor1

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# create a 3D tensor with values 1 everywhere
tensor2 = torch.ones(1, 4, 5)

tensor2

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [8]:
"""
Exercise 2.2
Create a 3D PyTorch tensor with values 0 in it. Make the shape of the tensor (2, 3, 4)
"""

tensor = torch.zeros(2, 3 ,4)

tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
# we can also easily convert np arrays to tensor
import numpy as np

np_arr = np.array(range(10)) 
print(np_arr)

pt_tensor = torch.tensor(np_arr, dtype=torch.int)
print(pt_tensor)

[0 1 2 3 4 5 6 7 8 9]
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)


2.1.2 Index and slice PyTorch tensors

In [10]:
# height of the third president
height = heights_tensor[2]

height

tensor(189., dtype=torch.float64)

In [11]:
# we can use negative indexing to count from the back of the tensor
height = heights_tensor[-2]

height

tensor(191., dtype=torch.float64)

In [12]:
# tensor slicing
five_heights = heights_tensor[-5:]

five_heights

tensor([188., 182., 185., 191., 183.], dtype=torch.float64)

In [13]:
""""
Exercise 2.3
Use slicing to obtain the heights of the first five U.S. presidents in the tensor
heights_tensor.
"""
first_five = heights_tensor[:5]

first_five


tensor([189., 170., 189., 163., 183.], dtype=torch.float64)

2.1.3 PyTorch tensor shapes

In [14]:
# its a 1D tensor with 46 values
print(heights_tensor.shape)

torch.Size([46])


In [15]:
# convert from cm to ft
heights_in_feet = heights_tensor / 30.48

heights_in_feet

tensor([6.2008, 5.5774, 6.2008, 5.3478, 6.0039, 5.6102, 6.0696, 5.5118, 5.6759,
        6.0039, 5.6759, 5.6759, 5.7415, 5.8399, 6.0039, 6.3320, 5.8399, 5.6759,
        5.7087, 6.0039, 6.0039, 5.9055, 5.5118, 5.9055, 5.5774, 5.8399, 5.9711,
        5.9055, 6.0039, 5.8399, 5.9711, 6.1680, 5.7415, 5.8727, 6.0039, 6.3320,
        5.9711, 6.0039, 5.8071, 6.0696, 6.1680, 6.1680, 5.9711, 6.0696, 6.2664,
        6.0039], dtype=torch.float64)

In [16]:
# we can use torch.cat to concatenate two tensors
# dim=0 means we concatenate them along the first dimension
# we get a 1D tensor with 92 values
heights_2_measures = torch.cat([heights_tensor, heights_in_feet], dim=0)

heights_2_measures.shape

torch.Size([92])

In [17]:
# reshape it into a 2D tensor with two rows and 46 columns
# first row in cm and second row in ft
heights_reshaped = heights_2_measures.reshape(2, 46)

heights_reshaped, heights_reshaped.shape

(tensor([[189.0000, 170.0000, 189.0000, 163.0000, 183.0000, 171.0000, 185.0000,
          168.0000, 173.0000, 183.0000, 173.0000, 173.0000, 175.0000, 178.0000,
          183.0000, 193.0000, 178.0000, 173.0000, 174.0000, 183.0000, 183.0000,
          180.0000, 168.0000, 180.0000, 170.0000, 178.0000, 182.0000, 180.0000,
          183.0000, 178.0000, 182.0000, 188.0000, 175.0000, 179.0000, 183.0000,
          193.0000, 182.0000, 183.0000, 177.0000, 185.0000, 188.0000, 188.0000,
          182.0000, 185.0000, 191.0000, 183.0000],
         [  6.2008,   5.5774,   6.2008,   5.3478,   6.0039,   5.6102,   6.0696,
            5.5118,   5.6759,   6.0039,   5.6759,   5.6759,   5.7415,   5.8399,
            6.0039,   6.3320,   5.8399,   5.6759,   5.7087,   6.0039,   6.0039,
            5.9055,   5.5118,   5.9055,   5.5774,   5.8399,   5.9711,   5.9055,
            6.0039,   5.8399,   5.9711,   6.1680,   5.7415,   5.8727,   6.0039,
            6.3320,   5.9711,   6.0039,   5.8071,   6.0696,   6.1680,

In [18]:
# we can index and slice multidimensional tensors
print(heights_reshaped[1,-2])

tensor(6.2664, dtype=torch.float64)


In [19]:
"""" 
Exercise 2.4
Use indexing to obtain the height of Joe Biden in the tensor heights_reshaped in
centimeters
"""

height = heights_reshaped[0, -1]

height

tensor(183., dtype=torch.float64)

2.1.4 Mathematical operations on PyTorch tensors

In [ ]:
# median height
torch.median(heights_reshaped[0,:])

tensor(182., dtype=torch.float64)

In [25]:
# average height in both rows (dim=1)
torch.mean(heights_reshaped,dim=1)

tensor([180.0652,   5.9077], dtype=torch.float64)

In [27]:
# tallest president
# torch.max returns two tensors
values, indices = torch.max(heights_reshaped, dim=1)

values, indices

(tensor([193.0000,   6.3320], dtype=torch.float64), tensor([15, 15]))

In [28]:
"""
Exercise 2.5
Use the torch.min() method to find out the index and height of the shortest U.S president.
"""

value, index = torch.min(heights_reshaped, dim=1)

value, index

(tensor([163.0000,   5.3478], dtype=torch.float64), tensor([3, 3]))